---

- name: Create Deployment User aka "DEPLOYER!!!"
  user: |
    name="{{ deployer__username }}"
    password="{{ deployer__password }}"
    group="{{ deployer__group_primary }}"
    shell="{{ deployer__shell }}"
    generate_ssh_key=yes
    append=yes
    state=present
  register: deployer_created

- name: Add deployment user groups
  when: deployer_created|success
  user: |
    name="{{ deployer__username }}"
    groups="{{ item }}"
  with_items: deployer__groups_to_join

- name: Add Deployer Authorised Key
  authorized_key:
    user="{{ deployer__username }}"
    key="{{ deployer__public_key }}"
    state=present

- name: Ensure github.com/bitbucket.org are a known host
  lineinfile:
    dest: "/home/{{ deployer__username }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ item.domain }}"
    regexp: "{{ item.regexp }}"
  with_items:
    - { domain: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}", regexp: '^github\.com' }
    - { domain: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}", regexp: '^bitbucket\.org' }
