---

- name: Create deployment group
  group:
    name: "{{ deployer__group_primary }}"
    state: present
  register: deployer_group_created

- name: Create secondary groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ deployer__groups_to_join }}"
  register: deployer_secondary_groups_created

- name: Create deployment user"
  when: deployer_group_created|success
  user: |
    name="{{ deployer__username }}"
    password="{{ deployer__password }}"
    group="{{ deployer__group_primary }}"
    shell="{{ deployer__shell }}"
    generate_ssh_key=yes
    append=yes
    state=present
  register: deployer_created

- name: Add deployment user groups
  when: deployer_created|success
  user: >
    name="{{ deployer__username }}"
    groups="{{ deployer__groups_to_join | join(',') }}"

- name: Add Deployer Authorised Key
  when: deployer_created|success
  authorized_key:
    user="{{ deployer__username }}"
    key="{{ item }}"
    state=present
  with_items: "{{ deployer__public_keys }}"

- name: Ensure github.com/bitbucket.org are a known host
  when: deployer_created|success
  lineinfile:
    dest: "/home/{{ deployer__username }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ item.domain }}"
    regexp: "{{ item.regexp }}"
  with_items:
    - { domain: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}", regexp: '^github\.com' }
    - { domain: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}", regexp: '^bitbucket\.org' }
    - { domain: "{{ lookup('pipe', 'ssh-keyscan -t rsa gitlab.com') }}", regexp: '^gitlab\.com' }

- name: Create sudoer.d configuration for deployer in /etc/sudoers.d/
  when: deployer_created|success
  template:
    src: "sudoers.d.tmpl.j2"
    dest: "/etc/sudoers.d/{{ item.filename }}"
    mode: "0440"
    owner: root
    group: root
    validate: /usr/sbin/visudo -c -f %s
  with_items: "{{ deployer__sudoer_abilities }}"
